//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompClub.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Computers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Computers()
        {
            this.Sessions = new HashSet<Sessions>();
        }
    
        public int compId { get; set; }
        public int tariff_typeId { get; set; }
        public string processor { get; set; }
        public string videocard { get; set; }
        public string ram { get; set; }
        public string monitor { get; set; }
        public string keyboard { get; set; }
        public string mouse { get; set; }
        public bool workability { get; set; }
    
        public virtual Types_tarrif Types_tarrif { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sessions> Sessions { get; set; }
    }
}
