//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompClub.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Programms
    {
        public int idProgramm { get; set; }
        public string name { get; set; }
        public string img_path { get; set; }
        public string file_path { get; set; }
        public string category { get; set; }
        public string process_name { get; set; }
    }
}
